### ISSUE TITLE
PdiffFailedError: Could not resize reference image to size of new image

### ISSUE THREAD

**Issue by pitchandtone** [bslatkin/dpxdt#102]
I'm getting the before and after images generating properly, but pdiff fails due to error above.

Can anyone point me in the right direction to solve this?

**Comment by elsigh** [comment]
I actually get this error on my deployed instance occasionally.

**Comment by elsigh** [comment]
I think it's with a rather large image, but worth mentioning.
Error in workflow=dpxdt.client.pdiff_worker.DoPdiffQueueWorkflow({args: (), parent: dpxdt.client.queue_worker.DoTaskWorkflow#65191120, kwargs: {build_id: 1, reference_sha1sum: u'82b5a45f8ff1ab495a3060a3d0989ee6ede42982', release_number: 1, run_sha1sum: u'82b5a45f8ff1ab495a3060a3d0989ee6ede42982', run_name: u'Phone :: Enthusiasts', heartbeat: <function heartbeat at 0x4ee5398>, release_name: u'circleci-5309 by elsigh'}})#80232848 from item=dpxdt.client.pdiff_worker.ResizeWorkflow({parent: dpxdt.client.pdiff_worker.DoPdiffQueueWorkflow#80232848, kwargs: {timeout_seconds: 60}, args: ('/tmp/tmpHaHEno/log.txt',), resized_ref_path: '/tmp/tmpHaHEno/ref_resized', result: 1, ref_path: '/tmp/tmpHaHEno/ref', done: True, run_path: '/tmp/tmpHaHEno/run'})#69226896, error=None
Traceback (most recent call last):
  File "/home/vmagent/app/dpxdt/client/workers.py", line 459, in handle_item
    next_item = generator.send(item.result)
  File "/home/vmagent/app/dpxdt/client/pdiff_worker.py", line 183, in run
    'Could not resize reference image to size of new image')
PdiffFailedError: Could not resize reference image to size of new image

**Comment by elsigh** [comment]
heh, I wonder if the reason has to do with this next error I see:
FetchThread:140054464915200 error item=dpxdt.client.fetch_worker.FetchItem({username: 'wpvisvlzkaqsankcbvohf7dkkgbr2biw', result_path: '/tmp/tmpdWqgfF/run', parent: dpxdt.client.release_worker.DownloadArtifactWorkflow#81232528, url: u'http://shiftdpxdt.appspot.com/api/download?sha1sum=82b5a45f8ff1ab495a3060a3d0989ee6ede42982&build_...', status_code: 200, timeout_seconds: 30, content_type: u'image/png', error: (<type 'exceptions.IOError'>, IOError(28, 'No space left on device'), <traceback object at 0x4313ab8...), post: None, password: 'ELIDED', data: None, _data_json: None})#86024656
Traceback (most recent call last):
  File "/home/vmagent/app/dpxdt/client/workers.py", line 137, in run
    next_item = self.handle_item(item)
  File "/home/vmagent/app/dpxdt/client/fetch_worker.py", line 230, in handle_item
    return fetch_internal(item, request)
  File "/home/vmagent/app/dpxdt/client/fetch_worker.py", line 156, in fetch_internal
    result_file.write(piece)
IOError: [Errno 28] No space left on device

**Comment by bslatkin** [comment]
Probably. That's why I suggest installing this package:

https://packages.debian.org/wheezy/tmpreaper

**Comment by elsigh** [comment]
Oddly, tmpreaper is enabled in the `Docker` file

**Comment by bslatkin** [comment]
It could be that it's not being activated properly. IIRC you have to edit the config file in /etc/ to properly start the cronjob. I bet that changed or never worked.

**Comment by elsigh** [comment]
I tried testing that theory yesterday but there's apparently a new bug in Mac OSX security update that causes boot2docker to just crash your machine. I figured that out the second time, and updated virtualbox.. then tried to get running locally without much luck.. I was hoping I could just shell into the instance and see what the config looked like.. Still investigating.
