### ISSUE TITLE
PdiffFailedError: Could not resize reference image to size of new image

### ISSUE THREAD

**Issue by santthosh** [bslatkin/dpxdt#114]
Any ideas how to resolve this issue?

```
ERROR workers.py:452] Error in workflow=dpxdt.client.pdiff_worker.DoPdiffQueueWorkflow({args: (), parent: dpxdt.client.queue_worker.DoTaskWorkflow({args: ('http://localhost:80/api/work_queue/run-pdiff', <cl...8, kwargs: {build_id: 1, reference_sha1sum: u'a177b4f676168270d016444b23b24f8dfb46c4de', release_number: 1, run_sha1sum: u'5b837ec806dd7bfded2e8223f4b4cfeedc0cadd4', run_name: u"'self#4'", heartbeat: <function heartbeat at 0x2b939b0>, release_name: u"'test.qa.acme.com'"}})#45775760 from item=dpxdt.client.pdiff_worker.ResizeWorkflow({parent: dpxdt.client.pdiff_worker.DoPdiffQueueWorkflow({args: (), parent: dpxdt.client.queue_worker.DoTaskWo...0, kwargs: {timeout_seconds: 20}, args: ('/tmp/tmp9ksvPH/log.txt',), resized_ref_path: '/tmp/tmp9ksvPH/ref_resized', result: 1, ref_path: '/tmp/tmp9ksvPH/ref', done: True, run_path: '/tmp/tmp9ksvPH/run'})#45773648, error=None
Traceback (most recent call last):
  File "/home/ec2-user/dpxdt-mirror/dpxdt/client/workers.py", line 435, in handle_item
    next_item = generator.send(item.result)
  File "/home/ec2-user/dpxdt-mirror/dpxdt/client/pdiff_worker.py", line 182, in run
    'Could not resize reference image to size of new image')
PdiffFailedError: Could not resize reference image to size of new image
```

**Comment by bslatkin** [comment]
I added a check in 6fe0d173e29e5319d3a34b3903ecfd703306f96e to make sure image magick is installed correctly. That should help this one.
