### ISSUE TITLE
Errors when ImageMagick is not installed are not too helpful

### ISSUE THREAD

**Issue by tavinathanson** [bslatkin/dpxdt#119]
I tried running `dpxdt test`, and it took me a while to figure out that the error I saw was due to not installing ImageMagick. (I eventually figured it out thanks to #10.)

My error was the following:

```
dpxdt test __tests__/pdifftests
Running setup step
  logging to /tmp/tmpJMlmcB/setup.log
Request for http://localhost:5001/ succeeded, continuing with tests...
examine: Running webpage capture process
examine:   Logging to /tmp/tmpJMlmcB/tmpRkDnhu/log.txt
examine: Resizing reference image
item=dpxdt.client.pdiff_worker.ResizeWorkflow({parent: dpxdt.tools.local_pdiff.CaptureAndDiffWorkflowItem({args: ('examine', '/tmp/tmpJMlmcB/tmpRkDnhu/log....4, kwargs: {timeout_seconds: 60}, args: ('/tmp/tmpJMlmcB/tmpRkDnhu/log.txt',), resized_ref_path: '/tmp/tmpJMlmcB/tmpRkDnhu/ref_resized', ref_path: '__tests__/pdifftests/examine.png', run_path: '/tmp/tmpJMlmcB/tmpRkDnhu/screenshot.png'})#4422966736 Failed to run subprocess: ['composite', '-compose', 'src', '-gravity', 'NorthWest', '__tests__/pdifftests/examine.png', '/tmp/tmpJMlmcB/tmpRkDnhu/screenshot.png', '/tmp/tmpJMlmcB/tmpRkDnhu/ref_resized']
Error in workflow=dpxdt.client.pdiff_worker.ResizeWorkflow({parent: dpxdt.tools.local_pdiff.CaptureAndDiffWorkflowItem({args: ('examine', '/tmp/tmpJMlmcB/tmpRkDnhu/log....4, kwargs: {timeout_seconds: 60}, args: ('/tmp/tmpJMlmcB/tmpRkDnhu/log.txt',), resized_ref_path: '/tmp/tmpJMlmcB/tmpRkDnhu/ref_resized', ref_path: '__tests__/pdifftests/examine.png', run_path: '/tmp/tmpJMlmcB/tmpRkDnhu/screenshot.png'})#4422966736 from item=None, error=False
OSError: [Errno 2] No such file or directory

Traceback (most recent call last):
  File "/Users/tavi/.virtualenvs/cycledash/bin/dpxdt", line 9, in <module>
    load_entry_point('dpxdt==0.1.5', 'console_scripts', 'dpxdt')()
  File "/Users/tavi/.virtualenvs/cycledash/lib/python2.7/site-packages/dpxdt/tools/local_pdiff.py", line 509, in run
    main(sys.argv)
  File "/Users/tavi/.virtualenvs/cycledash/lib/python2.7/site-packages/dpxdt/tools/local_pdiff.py", line 490, in main
    coordinator.wait_one()
  File "/Users/tavi/.virtualenvs/cycledash/lib/python2.7/site-packages/dpxdt/client/workers.py", line 345, in wait_one
    item.check_result()
  File "/Users/tavi/.virtualenvs/cycledash/lib/python2.7/site-packages/dpxdt/client/workers.py", line 430, in handle_item
    next_item = generator.throw(*error)
  File "/Users/tavi/.virtualenvs/cycledash/lib/python2.7/site-packages/dpxdt/tools/local_pdiff.py", line 385, in run
    yield RunTestSuiteWorkflowItem(config_dir, config, mode, heartbeat)
  File "/Users/tavi/.virtualenvs/cycledash/lib/python2.7/site-packages/dpxdt/client/workers.py", line 430, in handle_item
    next_item = generator.throw(*error)
  File "/Users/tavi/.virtualenvs/cycledash/lib/python2.7/site-packages/dpxdt/tools/local_pdiff.py", line 414, in run
    heartbeat=heartbeat)
  File "/Users/tavi/.virtualenvs/cycledash/lib/python2.7/site-packages/dpxdt/client/workers.py", line 430, in handle_item
    next_item = generator.throw(*error)
  File "/Users/tavi/.virtualenvs/cycledash/lib/python2.7/site-packages/dpxdt/tools/local_pdiff.py", line 148, in run
    heartbeat=NamedHeartbeat)
  File "/Users/tavi/.virtualenvs/cycledash/lib/python2.7/site-packages/dpxdt/client/workers.py", line 430, in handle_item
    next_item = generator.throw(*error)
  File "/Users/tavi/.virtualenvs/cycledash/lib/python2.7/site-packages/dpxdt/tools/local_pdiff.py", line 193, in run
    log_file, ref_path, output_path, ref_resized_path)
  File "/Users/tavi/.virtualenvs/cycledash/lib/python2.7/site-packages/dpxdt/client/workers.py", line 440, in handle_item
    next_item = generator.send(item)
  File "/Users/tavi/.virtualenvs/cycledash/lib/python2.7/site-packages/dpxdt/client/process_worker.py", line 64, in run
    close_fds=True)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by bslatkin** [comment]
I addressed this in c5b92c2f411871673fe66b9801d2fe3a7db7c675 with dpxdt/client/utils.py
